# Generated by Django 5.2.8 on 2025-12-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediampesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaTransaction',
            new_name='Transactions',
        ),
    ]
