# Generated by Django 5.2.8 on 2025-12-10 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('air_quality', 'Air Quality'), ('waste', 'Waste Management'), ('water', 'Water Levels'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, help_text='Measurement value', max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., ppm, kg, liters)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_recorded', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
